parameters:
#    melnik_homework.example.class: Melnik\HomeworkBundle\Example

services:
#    melnik_homework.example:
#        class: %melnik_homework.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
